project_id = "rwjpgwgeosrldramrgvq"

[functions.process-email-queue]
verify_jwt = false

[functions.nuki-integration]
verify_jwt = false

[functions.update-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.bookings-list]
verify_jwt = false

[functions.availability]
verify_jwt = false

[functions.booking-create]
verify_jwt = false

[functions.customer-history]
verify_jwt = false

[functions.nuki-webhook]
verify_jwt = false

[functions.booking-scheduler]
verify_jwt = false

[functions.coach-generate]
verify_jwt = false

[functions.label-book]
verify_jwt = false

[functions.label-invoice]
verify_jwt = false

[functions.create-gift-card]
verify_jwt = false

[functions.redeem-gift-card]
verify_jwt = false